name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 2 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 1.1.4,1.1.5 ]
        variant: [ server ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=repository::${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})
          echo ::set-output name=tag::${{ matrix.major }}
          echo ::set-output name=workdir::${{ matrix.major }}/${{ matrix.variant }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.tag }}
